name: Check
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/setup
      - run: pnpm build

  tsc:
    name: Typescript Compiler
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/setup
      - run: pnpm tsgo:check

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/setup
      - run: pnpm prettier

  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/setup
      - run: pnpm eslint

  commitlint:
    name: CommitLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/setup
      - if: github.event_name == 'push'
        run: pnpm exec commitlint -- --last --verbose
      - if: github.event_name == 'pull_request'
        run: pnpm exec commitlint -- --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
